sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    point_cloud_topic: /camera/depth_registered/points
    point_cloud_topic: /senz3d/depth/points
    filtered_cloud_topic: filtered_cloud
    max_range: 1.0
    point_subsample: 1
    padding_offset: 0.03
    padding_scale: 1.0

#  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#    image_topic: /senz3d/depth/image_raw
#    queue_size: 5
#    near_clipping_plane_distance: 0.1
#    far_clipping_plane_distance: 1.0
#    skip_vertical_pixels: 1
#    skip_horizontal_pixels: 1
    
    #shadow_threshold: 0.2
    #padding_scale: 4.0
    #padding_offset: 0.04
    #filtered_cloud_topic: output_cloud